---
#
- hosts: servers1c
  remote_user: root

  tasks:
      - name: yum update
        yum: 
            name: '*'
            state: latest
            
      - name: Epel
        yum:
            name: 
                - epel-release
            state: present

      - name: Install packages
        yum:
            name:
                - bzip2
                - readline
                - krb5-libs
                - openssl
                - tcl
                - libicu
                - libicu-devel
                - systemd-sysv
                - wget
                - mc
            state: present

      - name: Set as default locale
        command: localectl set-locale LANG=ru_RU.UTF-8

      - name: Copy srv1c rpm files
        copy:
                src: ./rpms
                dest: /tmp/

      - name: Install 1c server rpms
        shell: yum localinstall -y *rpm
        args:
            chdir: /tmp/rpms
            warn: no

      - name: Create PG cluster 
        shell: /usr/pgsql-10/bin/postgresql-10-setup initdb

      - name: postgresql-10 start
        service:
            name: postgresql-10
            enabled: yes
            state: started

      - name: Set password
        become: yes
        become_user: postgres
        become_method: su
        become_flags: '-l'
        command: psql -c "alter user postgres with password 'changeme';"

...

