---
#
- hosts: servers1c
  remote_user: root

  tasks:
      - name: yum update
        yum: 
            name: '*'
            state: latest
            
      - name: Epel
        yum:
            name: 
                - epel-release
            state: present

      - name: Install packages
        yum:
            name:
                - bzip2
                - readline
                - krb5-libs
                - openssl
                - tcl
                - libicu
                - libicu-devel
                - systemd-sysv
                - wget
                - centos-release-scl
                - mc
            state: present

      - name: Set as default locale
        command: localectl set-locale LANG=ru_RU.UTF-8

      - name: Copy srv1c rpm files
        copy:
                src: ./rpms
                dest: /tmp/

      - name: Install 1c postgresql-11 rpms
        shell: yum localinstall -y *rpm
        args:
            chdir: /tmp/rpms
            warn: no

      - name: Create PG cluster 
        shell: /usr/pgsql-11/bin/postgresql-11-setup initdb

      - name: postgresql-11 start
        service:
            name: postgresql-11
            state: started

      - name: postgresql config edit 
        become: yes
        become_user: postgres
        become_method: su
        become_flags: '-l'
        block:
            - replace:
                path: '11/data/pg_hba.conf'
                backup: yes
                before: 'local\s+replication'
                regexp: 'ident'
                replace: 'md5'
            - command: psql -c "alter user postgres with password 'changepgpass';"
            - lineinfile:
                  path: '11/data/postgresql.conf'          
                  line: 'shared_buffers = 2048MB' 
                  regexp: 'shared_buffers\s*='
                  backup: yes
            - lineinfile:
                  path: '11/data/postgresql.conf'          
                  line: "{{ item.line }}"
                  regexp: "{{ item.regexp }}"
              loop:
                  - { line: 'temp_buffers = 256MB', regexp: 'temp_buffers\s*=' }
                  - { line: 'work_mem = 128MB', regexp: 'work_mem\s*=' }
                  - { line: 'maintenance_work_mem = 512MB', regexp: 'maintenance_work_mem\s*=' }
                  - { line: 'effective_cache_size = 6144MB', regexp: 'effective_cache_size\s*=' }
                  - { line: ' autovacuum = on', regexp: 'autovacuum\s*=' }
                  - { line: ' autovacuum_max_workers = 4', regexp: 'autovacuum_max_workers\s*=' }
                  - { line: ' fsync = off', regexp: 'fsync\s*=' }
                  - { line: ' synchronous_commit = off', regexp: 'synchronous_commit\s*=' }
                  - { line: ' min_wal_size = 512MB', regexp: 'min_wal_size\s*=' }
                  - { line: ' max_wal_size = 1024MB', regexp: 'max_wal_size\s*=' }

      - name: postgresql-11 restart
        service:
            name: postgresql-11
            enabled: yes
            state: restarted
              
...

